### ISSUE TITLE
Lock and Unlock Implementation

### ISSUE THREAD

**Issue by bnurbekov** [smartinick/esp32_xiaomi_m365#15]
Hi, thanks for the great work! It is very useful. 
I would like to implement the lock/unlock functionality. Please, can you give me some pointers on how to do that? Do I understand correctly that the current code only reads information, but does not transmit anything?
Thank you again.

**Comment by smartinick** [comment]
Sorry for forgetting to answer here.... :(

the code sends a lot of data.... because the scooter only sends gas/throttle state by itself, all the other data has to be requested....

anyway.... for your question.... that would work like this:

  #define commandlen 10
  uint8_t command[commandlen] = { 0x55,0xAA,0x04,0x20,0x03,0x01,0x02,0x03,0xB7,0xFF};
  #define command_cmd 5
  #define command_value1 6
  #define command_value2 7
  #define command_crcstart 2
  #define command_crc1 8
  #define command_crc2 9

void m365_sendcommand(uint8_t cvalue, uint8_t cparam1, uint8_t cparam2) {
  command[command_cmd] = cvalue;
  command[command_value1] = cparam1;
  command[command_value2] = cparam2;
  crccalc = 0x00;
  for(uint8_t i=command_crcstart;i<command_crc1;i++) {
    crccalc=crccalc + command[i];
  }
  crccalc = crccalc ^ 0xffff;
  command[command_crc1]=(uint8_t)(crccalc&0xff);
  command[command_crc2]=(uint8_t)((crccalc&0xff00)>>8);
  M365Serial.write((unsigned char*)&command,commandlen);
  commands_sent++;
} //m365_sendcommand

lock: m365_sendcommand(0x70,01,0);
unlock: m365_sendcommand(0x71,01,0);
